use opername instead of nickname when logging mask changes
Libera-Chat/maskwatch-bot pull request #9
Opened 2021-06-04 16:02 UTC by examknow

this is achieved by sending the opername instead of the nickname for the who parameter

2021-06-05 17:57 UTC, jesopo commented
see https://github.com/Libera-Chat/maskwatch-bot/issues/7#issuecomment-855274196

2021-06-06 00:16 UTC, examknow commented
forgot to mention, to update the db tables:

    ALTER TABLE changes ADD COLUMN by_oper TEXT;
    ALTER TABLE changes RENAME COLUMN by TO by_nick;

2021-06-14 21:05 UTC, examknow commented
Should be all ready now. In a future PR, I'd like to make the oper whois regexes configurable so that we can continue to easily support other ircds.

2021-06-14 22:50 UTC, jesopo requested changes

2021-06-14 22:50 UTC, jesopo commented on maskwatch-bot/__init__.py
> +            return whois_line.params[2].split(",")[0].split()[-1]
you won't always be told the privset, so sometimes you'll get
```
is opered as sandcat, privset sandcat
```
and sometimes you'll get
```
is opered as sandcat
```

so I'd instead suggest this
```python3
if whois_line.command == RPL_WHOISOPERATOR:
    match = re.search(r"^is opered as (\S+)(?:,|$)", whois_line.params[2])
    if match is not None:
        return match.group(1)
```

2021-06-14 22:50 UTC, jesopo commented on maskwatch-bot/__init__.py
> +        if whois_line.command == RPL_WHOISSPECIAL and whois_line.params[2].startswith("is opered as"):
I think this still wants to be `RPL_WHOISOPERATOR`

2021-06-14 23:00 UTC, jesopo commented on maskwatch-bot/__init__.py
> +            print(match)
the curse of the forgotten debug print

2021-06-14 23:01 UTC, jesopo commented on maskwatch-bot/__init__.py
> +                outs = await getattr(self, attrib)(opername, who._source, args)
`str(who)` instead of `who._source`

2021-06-14 23:05 UTC, merged